#! /usr/bin/bash

PACKAGENAME="$2"

usage() {
    cat << EOF
Usage: pachelpr [OPTIONS] [PACKAGE_NAME]

Options:
    -i, --install   Install PACKAGE_NAME from the offical repos
    -r, --remove    Remove PACKAGE_NAME and its dependencies
    -s, --search    Searches the arch repos for a package
    -a, --aur       Downloads and installs a package from the AUR.
    -u, --update    Does a full system upgrade
    --help          Display this help message
EOF
exit 0
}

[[ $1 == "--help" ]] && usage

[[ "$1" == "--install" ]] && sudo pacman -S "$PACKAGENAME"

